#!/usr/bin/env python3
# modules/report.py — Advanced HTML + JSON + Markdown Report

import os, json, time
from core.utils import count_lines, safe_read

class ReportGenerator:
    def __init__(self, pipeline):
        self.p   = pipeline
        self.f   = pipeline.files
        self.out = pipeline.out
        self.pfx = pipeline.prefix

    def generate(self) -> str:
        target   = self.p.target
        findings = self.p.findings
        elapsed  = time.time() - self.p.start_t
        scan_date= time.strftime("%Y-%m-%d %H:%M:%S")

        subs  = count_lines(self.f["subdomains"])
        live  = count_lines(self.f["live_hosts"])
        urls  = count_lines(self.f["urls"])
        ports = count_lines(self.f["open_ports"])
        js_s  = count_lines(self.f["js_secrets"])
        crit  = sum(1 for f in findings if f["severity"]=="critical")
        high  = sum(1 for f in findings if f["severity"]=="high")
        med   = sum(1 for f in findings if f["severity"]=="medium")
        low   = sum(1 for f in findings if f["severity"]=="low")

        html_path = os.path.join(self.out, f"{self.pfx}_report.html")
        json_path = os.path.join(self.out, f"{self.pfx}_findings.json")
        md_path   = os.path.join(self.out, f"{self.pfx}_report.md")

        with open(html_path,"w") as f:
            f.write(self._html(target,scan_date,elapsed,subs,live,urls,ports,js_s,
                                crit,high,med,low,findings))

        with open(json_path,"w") as f:
            json.dump({
                "tool":"M7Hunter v3.0","author":"Sharlix | MilkyWay Intelligence",
                "target":target,"scan_date":scan_date,"elapsed":round(elapsed,1),
                "stats":{"subdomains":subs,"live_hosts":live,"urls":urls,
                         "open_ports":ports,"js_secrets":js_s},
                "findings":findings
            },f,indent=2)

        with open(md_path,"w") as f:
            f.write(self._markdown(target,scan_date,elapsed,findings,subs,live))

        self.p.log.success(f"HTML   → {html_path}")
        self.p.log.success(f"JSON   → {json_path}")
        self.p.log.success(f"MD     → {md_path}")
        return html_path

    def _markdown(self, target, scan_date, elapsed, findings, subs, live):
        lines = [
            f"# M7Hunter v3.0 — Security Report",
            f"**Target:** {target}  ",
            f"**Date:** {scan_date}  ",
            f"**Duration:** {elapsed:.0f}s  ",
            f"**Subdomains:** {subs} | **Live Hosts:** {live}  ",
            f"**Total Findings:** {len(findings)}",
            "",
            "## Findings",
            "",
            "| Severity | Type | URL | Detail |",
            "|----------|------|-----|--------|",
        ]
        for f in sorted(findings, key=lambda x: ["critical","high","medium","low","info"].index(x.get("severity","info"))):
            url = f.get("url","")[:80]
            det = f.get("detail","")[:100]
            lines.append(f"| {f['severity'].upper()} | {f['type']} | `{url}` | {det} |")
        lines += ["","---","*Generated by M7Hunter v3.0 | MilkyWay Intelligence | Sharlix*"]
        return "\n".join(lines)

    def _html(self, target, scan_date, elapsed, subs, live, urls, ports, js_s,
               crit, high, med, low, findings):

        mode = ("STEALTH" if self.p.args.stealth else
                "DEEP"    if self.p.args.deep    else
                "QUICK"   if self.p.args.quick   else "CUSTOM")
        tor_status = (f"✅ ON | Exit IP: {self.p.tor.current_ip}"
                      if self.p.tor and self.p.tor.is_running() else "❌ OFF")
        oob_status = (f"✅ {self.p.oob.server}"
                      if self.p.oob else "❌ OFF")

        rows = ""
        for f in findings:
            sev   = f.get("severity","info")
            url_s = str(f.get("url",""))[:100]
            det_s = str(f.get("detail",""))[:120]
            rows += f"""<tr data-sev="{sev}">
              <td><span class="badge badge-{sev}">{sev.upper()}</span></td>
              <td>{f.get('type','')}</td>
              <td class="url-cell">{url_s}</td>
              <td>{det_s}</td>
              <td>{f.get('tool','')}</td>
              <td>{f.get('time','')}</td>
            </tr>"""

        steps_html = "".join(
            f'<span class="pstep">{s}</span>'
            for s in self.p.steps_to_run)

        file_grid = self._file_grid()

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>M7Hunter v3.0 — {target}</title>
<style>
:root{{--bg:#07070f;--card:#0f0f1c;--card2:#13131f;--border:#1e1e30;
  --red:#ff3860;--blue:#2563eb;--cyan:#00d4ff;--green:#00e676;
  --yellow:#ffd600;--text:#e0e0e0;--dim:#555;--white:#fff}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{background:var(--bg);color:var(--text);font-family:'Courier New',monospace;padding:20px}}
.banner{{text-align:center;padding:40px 0 24px}}
.tri-wrap{{display:inline-block;position:relative;margin-bottom:12px}}
.tri{{width:0;height:0;border-left:80px solid transparent;
  border-right:80px solid transparent;border-bottom:138px solid #1e3a8a;
  filter:drop-shadow(0 0 20px #2563eb)}}
.eye{{position:absolute;top:72px;left:50%;transform:translate(-50%,-50%);
  font-size:38px;animation:ep 2.5s ease-in-out infinite}}
@keyframes ep{{0%,100%{{opacity:1}}50%{{opacity:.6}}}}
h1{{font-size:2.4em;letter-spacing:5px;
  background:linear-gradient(135deg,#fff,#00d4ff,#fff);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;
  margin:8px 0;font-weight:900}}
.tl{{color:#00d4ff;font-size:.85em;letter-spacing:2px}}
.au{{color:#ff3860;font-size:.8em;margin-top:4px}}
.ln{{color:#2563eb;font-size:.7em;letter-spacing:1px;margin:4px 0}}
.stats{{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));
  gap:10px;margin:24px 0}}
.stat{{background:var(--card);border:1px solid var(--border);border-radius:10px;
  padding:16px 10px;text-align:center;transition:transform .2s}}
.stat:hover{{transform:translateY(-2px);border-color:var(--cyan)}}
.stat .num{{font-size:2.2em;font-weight:900;line-height:1}}
.stat .lbl{{font-size:.72em;color:var(--dim);margin-top:5px;
  text-transform:uppercase;letter-spacing:1px}}
.c-r{{color:var(--red)}}.c-g{{color:var(--green)}}
.c-c{{color:var(--cyan)}}.c-y{{color:var(--yellow)}}.c-w{{color:var(--white)}}
.sec{{margin:22px 0}}
.sec h2{{color:var(--cyan);border-bottom:1px solid var(--border);
  padding-bottom:7px;margin-bottom:12px;font-size:.95em;
  letter-spacing:2px;text-transform:uppercase}}
/* Filter bar */
.filter-bar{{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}}
.filter-btn{{background:var(--card2);border:1px solid var(--border);
  border-radius:20px;padding:4px 14px;font-size:.76em;color:var(--dim);
  cursor:pointer;transition:all .15s}}
.filter-btn:hover,.filter-btn.active{{border-color:var(--cyan);color:var(--cyan)}}
/* Search */
#search{{background:var(--card);border:1px solid var(--border);
  border-radius:6px;padding:6px 12px;color:var(--text);font-size:.82em;
  width:260px;outline:none}}
#search:focus{{border-color:var(--cyan)}}
table{{width:100%;border-collapse:collapse;font-size:.8em}}
th{{background:var(--card2);color:var(--cyan);padding:9px 8px;
  text-align:left;border:1px solid var(--border);font-size:.88em}}
td{{padding:7px 8px;border:1px solid var(--border);vertical-align:top}}
tr:nth-child(even) td{{background:#0b0b15}}
tr:hover td{{background:#10101d}}
tr.hidden{{display:none}}
.url-cell{{word-break:break-all;max-width:280px;font-size:.78em}}
.badge{{display:inline-block;padding:2px 7px;border-radius:4px;
  font-size:.7em;font-weight:700;text-transform:uppercase;letter-spacing:1px}}
.badge-critical{{background:#500;color:#ff8080;border:1px solid #ff3860}}
.badge-high{{background:#3d1500;color:#ff6b35;border:1px solid #ff6b35}}
.badge-medium{{background:#2d2600;color:#ffd600;border:1px solid #ffd600}}
.badge-low{{background:#002d10;color:#00e676;border:1px solid #00e676}}
.badge-info{{background:#001a2d;color:#00d4ff;border:1px solid #00d4ff}}
.pipeline{{display:flex;flex-wrap:wrap;gap:7px;margin:10px 0}}
.pstep{{background:var(--card2);border:1px solid var(--blue);
  border-radius:20px;padding:4px 12px;font-size:.76em;color:var(--cyan)}}
.file-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));
  gap:7px;margin:10px 0}}
.fi{{background:var(--card);border:1px solid var(--border);border-radius:6px;
  padding:7px 11px;font-size:.76em;display:flex;justify-content:space-between}}
.fi .fn{{color:var(--cyan)}}.fi .fc{{color:var(--dim)}}
.footer{{text-align:center;color:var(--dim);font-size:.7em;margin-top:36px;
  padding-top:18px;border-top:1px solid var(--border)}}
</style>
</head>
<body>
<div class="banner">
  <div class="tri-wrap"><div class="tri"></div><div class="eye">👁</div></div>
  <div class="ln">══════════════════════════════════════════════</div>
  <h1>M7HUNTER</h1>
  <div class="tl">World's #1 Bug Bounty &amp; Pentest Pipeline</div>
  <div class="au">Made by MilkyWay Intelligence &nbsp;|&nbsp; Author: Sharlix &nbsp;|&nbsp; v3.0.0</div>
  <div class="ln">══════════════════════════════════════════════</div>
</div>

<div class="stats">
  <div class="stat"><div class="num c-c">{subs}</div><div class="lbl">Subdomains</div></div>
  <div class="stat"><div class="num c-g">{live}</div><div class="lbl">Live Hosts</div></div>
  <div class="stat"><div class="num c-y">{urls}</div><div class="lbl">URLs</div></div>
  <div class="stat"><div class="num c-w">{ports}</div><div class="lbl">Open Ports</div></div>
  <div class="stat"><div class="num c-y">{js_s}</div><div class="lbl">JS Secrets</div></div>
  <div class="stat"><div class="num c-r">{crit}</div><div class="lbl">Critical</div></div>
  <div class="stat"><div class="num c-r">{high}</div><div class="lbl">High</div></div>
  <div class="stat"><div class="num c-y">{med}</div><div class="lbl">Medium</div></div>
  <div class="stat"><div class="num c-g">{low}</div><div class="lbl">Low</div></div>
  <div class="stat"><div class="num c-c">{int(elapsed//60)}</div><div class="lbl">Minutes</div></div>
</div>

<div class="sec">
  <h2>📋 Scan Info</h2>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Target</td><td>{target}</td></tr>
    <tr><td>Date</td><td>{scan_date}</td></tr>
    <tr><td>Mode</td><td>{mode}</td></tr>
    <tr><td>Threads</td><td>{self.p.args.threads}</td></tr>
    <tr><td>Tor</td><td>{tor_status}</td></tr>
    <tr><td>OOB/Interactsh</td><td>{oob_status}</td></tr>
    <tr><td>Duration</td><td>{elapsed:.1f}s ({elapsed/60:.1f} min)</td></tr>
    <tr><td>Output Dir</td><td>{self.out}</td></tr>
  </table>
</div>

<div class="sec">
  <h2>🔗 Pipeline</h2>
  <div class="pipeline">{steps_html}</div>
</div>

<div class="sec">
  <h2>📁 Output Files</h2>
  <div class="file-grid">{file_grid}</div>
</div>

<div class="sec">
  <h2>🚨 Findings ({len(findings)})</h2>
  <div class="filter-bar">
    <input type="text" id="search" placeholder="Search findings..." oninput="filterAll()">
    <button class="filter-btn active" onclick="setFilter('all',this)">All ({len(findings)})</button>
    <button class="filter-btn" onclick="setFilter('critical',this)">Critical ({crit})</button>
    <button class="filter-btn" onclick="setFilter('high',this)">High ({high})</button>
    <button class="filter-btn" onclick="setFilter('medium',this)">Medium ({med})</button>
    <button class="filter-btn" onclick="setFilter('low',this)">Low ({low})</button>
  </div>
  <table id="findings-table">
    <tr><th>Severity</th><th>Type</th><th>URL / Location</th><th>Detail</th><th>Tool</th><th>Time</th></tr>
    {rows if rows else "<tr><td colspan='6' style='text-align:center;color:var(--dim)'>No findings.</td></tr>"}
  </table>
</div>

<div class="footer">
  M7Hunter v3.0.0 | MilkyWay Intelligence | Author: Sharlix<br>
  Only test systems you own or have explicit written permission to test.<br>
  Generated: {scan_date}
</div>

<script>
var currentFilter='all';
function setFilter(sev,btn){{
  currentFilter=sev;
  document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));
  btn.classList.add('active');
  filterAll();
}}
function filterAll(){{
  var q=document.getElementById('search').value.toLowerCase();
  document.querySelectorAll('#findings-table tr[data-sev]').forEach(function(r){{
    var sevMatch=(currentFilter==='all'||r.dataset.sev===currentFilter);
    var txtMatch=!q||r.textContent.toLowerCase().includes(q);
    r.classList.toggle('hidden',!(sevMatch&&txtMatch));
  }});
}}
</script>
</body></html>"""

    def _file_grid(self):
        items = []
        for key,path in self.f.items():
            if "dir" in key or not path.endswith(".txt"):
                continue
            if os.path.isfile(path):
                n    = count_lines(path)
                name = os.path.basename(path)
                items.append(
                    f"<div class='fi'><span class='fn'>{name}</span>"
                    f"<span class='fc'>{n} lines</span></div>")
        return "\n".join(items) if items else "<p style='color:var(--dim)'>No files yet.</p>"
